// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"log"

	"bovs/internal/data/ent/migrate"

	"bovs/internal/data/ent/areacode"

	"entgo.io/ent"
	"entgo.io/ent/dialect"
	"entgo.io/ent/dialect/sql"
)

// Client is the client that holds all ent builders.
type Client struct {
	config
	// Schema is the client for creating, migrating and dropping schema.
	Schema *migrate.Schema
	// AreaCode is the client for interacting with the AreaCode builders.
	AreaCode *AreaCodeClient
}

// NewClient creates a new client configured with the given options.
func NewClient(opts ...Option) *Client {
	cfg := config{log: log.Println, hooks: &hooks{}, inters: &inters{}}
	cfg.options(opts...)
	client := &Client{config: cfg}
	client.init()
	return client
}

func (c *Client) init() {
	c.Schema = migrate.NewSchema(c.driver)
	c.AreaCode = NewAreaCodeClient(c.config)
}

type (
	// config is the configuration for the client and its builder.
	config struct {
		// driver used for executing database requests.
		driver dialect.Driver
		// debug enable a debug logging.
		debug bool
		// log used for logging on debug mode.
		log func(...any)
		// hooks to execute on mutations.
		hooks *hooks
		// interceptors to execute on queries.
		inters *inters
	}
	// Option function to configure the client.
	Option func(*config)
)

// options applies the options on the config object.
func (c *config) options(opts ...Option) {
	for _, opt := range opts {
		opt(c)
	}
	if c.debug {
		c.driver = dialect.Debug(c.driver, c.log)
	}
}

// Debug enables debug logging on the ent.Driver.
func Debug() Option {
	return func(c *config) {
		c.debug = true
	}
}

// Log sets the logging function for debug mode.
func Log(fn func(...any)) Option {
	return func(c *config) {
		c.log = fn
	}
}

// Driver configures the client driver.
func Driver(driver dialect.Driver) Option {
	return func(c *config) {
		c.driver = driver
	}
}

// Open opens a database/sql.DB specified by the driver name and
// the data source name, and returns a new client attached to it.
// Optional parameters can be added for configuring the client.
func Open(driverName, dataSourceName string, options ...Option) (*Client, error) {
	switch driverName {
	case dialect.MySQL, dialect.Postgres, dialect.SQLite:
		drv, err := sql.Open(driverName, dataSourceName)
		if err != nil {
			return nil, err
		}
		return NewClient(append(options, Driver(drv))...), nil
	default:
		return nil, fmt.Errorf("unsupported driver: %q", driverName)
	}
}

// Tx returns a new transactional client. The provided context
// is used until the transaction is committed or rolled back.
func (c *Client) Tx(ctx context.Context) (*Tx, error) {
	if _, ok := c.driver.(*txDriver); ok {
		return nil, errors.New("ent: cannot start a transaction within a transaction")
	}
	tx, err := newTx(ctx, c.driver)
	if err != nil {
		return nil, fmt.Errorf("ent: starting a transaction: %w", err)
	}
	cfg := c.config
	cfg.driver = tx
	return &Tx{
		ctx:      ctx,
		config:   cfg,
		AreaCode: NewAreaCodeClient(cfg),
	}, nil
}

// BeginTx returns a transactional client with specified options.
func (c *Client) BeginTx(ctx context.Context, opts *sql.TxOptions) (*Tx, error) {
	if _, ok := c.driver.(*txDriver); ok {
		return nil, errors.New("ent: cannot start a transaction within a transaction")
	}
	tx, err := c.driver.(interface {
		BeginTx(context.Context, *sql.TxOptions) (dialect.Tx, error)
	}).BeginTx(ctx, opts)
	if err != nil {
		return nil, fmt.Errorf("ent: starting a transaction: %w", err)
	}
	cfg := c.config
	cfg.driver = &txDriver{tx: tx, drv: c.driver}
	return &Tx{
		ctx:      ctx,
		config:   cfg,
		AreaCode: NewAreaCodeClient(cfg),
	}, nil
}

// Debug returns a new debug-client. It's used to get verbose logging on specific operations.
//
//	client.Debug().
//		AreaCode.
//		Query().
//		Count(ctx)
//
func (c *Client) Debug() *Client {
	if c.debug {
		return c
	}
	cfg := c.config
	cfg.driver = dialect.Debug(c.driver, c.log)
	client := &Client{config: cfg}
	client.init()
	return client
}

// Close closes the database connection and prevents new queries from starting.
func (c *Client) Close() error {
	return c.driver.Close()
}

// Use adds the mutation hooks to all the entity clients.
// In order to add hooks to a specific client, call: `client.Node.Use(...)`.
func (c *Client) Use(hooks ...Hook) {
	c.AreaCode.Use(hooks...)
}

// Intercept adds the query interceptors to all the entity clients.
// In order to add interceptors to a specific client, call: `client.Node.Intercept(...)`.
func (c *Client) Intercept(interceptors ...Interceptor) {
	c.AreaCode.Intercept(interceptors...)
}

// Mutate implements the ent.Mutator interface.
func (c *Client) Mutate(ctx context.Context, m Mutation) (Value, error) {
	switch m := m.(type) {
	case *AreaCodeMutation:
		return c.AreaCode.mutate(ctx, m)
	default:
		return nil, fmt.Errorf("ent: unknown mutation type %T", m)
	}
}

// AreaCodeClient is a client for the AreaCode schema.
type AreaCodeClient struct {
	config
}

// NewAreaCodeClient returns a client for the AreaCode from the given config.
func NewAreaCodeClient(c config) *AreaCodeClient {
	return &AreaCodeClient{config: c}
}

// Use adds a list of mutation hooks to the hooks stack.
// A call to `Use(f, g, h)` equals to `areacode.Hooks(f(g(h())))`.
func (c *AreaCodeClient) Use(hooks ...Hook) {
	c.hooks.AreaCode = append(c.hooks.AreaCode, hooks...)
}

// Intercept adds a list of query interceptors to the interceptors stack.
// A call to `Intercept(f, g, h)` equals to `areacode.Intercept(f(g(h())))`.
func (c *AreaCodeClient) Intercept(interceptors ...Interceptor) {
	c.inters.AreaCode = append(c.inters.AreaCode, interceptors...)
}

// Create returns a builder for creating a AreaCode entity.
func (c *AreaCodeClient) Create() *AreaCodeCreate {
	mutation := newAreaCodeMutation(c.config, OpCreate)
	return &AreaCodeCreate{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// CreateBulk returns a builder for creating a bulk of AreaCode entities.
func (c *AreaCodeClient) CreateBulk(builders ...*AreaCodeCreate) *AreaCodeCreateBulk {
	return &AreaCodeCreateBulk{config: c.config, builders: builders}
}

// Update returns an update builder for AreaCode.
func (c *AreaCodeClient) Update() *AreaCodeUpdate {
	mutation := newAreaCodeMutation(c.config, OpUpdate)
	return &AreaCodeUpdate{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// UpdateOne returns an update builder for the given entity.
func (c *AreaCodeClient) UpdateOne(ac *AreaCode) *AreaCodeUpdateOne {
	mutation := newAreaCodeMutation(c.config, OpUpdateOne, withAreaCode(ac))
	return &AreaCodeUpdateOne{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// UpdateOneID returns an update builder for the given id.
func (c *AreaCodeClient) UpdateOneID(id int) *AreaCodeUpdateOne {
	mutation := newAreaCodeMutation(c.config, OpUpdateOne, withAreaCodeID(id))
	return &AreaCodeUpdateOne{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// Delete returns a delete builder for AreaCode.
func (c *AreaCodeClient) Delete() *AreaCodeDelete {
	mutation := newAreaCodeMutation(c.config, OpDelete)
	return &AreaCodeDelete{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// DeleteOne returns a builder for deleting the given entity.
func (c *AreaCodeClient) DeleteOne(ac *AreaCode) *AreaCodeDeleteOne {
	return c.DeleteOneID(ac.ID)
}

// DeleteOneID returns a builder for deleting the given entity by its id.
func (c *AreaCodeClient) DeleteOneID(id int) *AreaCodeDeleteOne {
	builder := c.Delete().Where(areacode.ID(id))
	builder.mutation.id = &id
	builder.mutation.op = OpDeleteOne
	return &AreaCodeDeleteOne{builder}
}

// Query returns a query builder for AreaCode.
func (c *AreaCodeClient) Query() *AreaCodeQuery {
	return &AreaCodeQuery{
		config: c.config,
		ctx:    &QueryContext{Type: TypeAreaCode},
		inters: c.Interceptors(),
	}
}

// Get returns a AreaCode entity by its id.
func (c *AreaCodeClient) Get(ctx context.Context, id int) (*AreaCode, error) {
	return c.Query().Where(areacode.ID(id)).Only(ctx)
}

// GetX is like Get, but panics if an error occurs.
func (c *AreaCodeClient) GetX(ctx context.Context, id int) *AreaCode {
	obj, err := c.Get(ctx, id)
	if err != nil {
		panic(err)
	}
	return obj
}

// Hooks returns the client hooks.
func (c *AreaCodeClient) Hooks() []Hook {
	return c.hooks.AreaCode
}

// Interceptors returns the client interceptors.
func (c *AreaCodeClient) Interceptors() []Interceptor {
	return c.inters.AreaCode
}

func (c *AreaCodeClient) mutate(ctx context.Context, m *AreaCodeMutation) (Value, error) {
	switch m.Op() {
	case OpCreate:
		return (&AreaCodeCreate{config: c.config, hooks: c.Hooks(), mutation: m}).Save(ctx)
	case OpUpdate:
		return (&AreaCodeUpdate{config: c.config, hooks: c.Hooks(), mutation: m}).Save(ctx)
	case OpUpdateOne:
		return (&AreaCodeUpdateOne{config: c.config, hooks: c.Hooks(), mutation: m}).Save(ctx)
	case OpDelete, OpDeleteOne:
		return (&AreaCodeDelete{config: c.config, hooks: c.Hooks(), mutation: m}).Exec(ctx)
	default:
		return nil, fmt.Errorf("ent: unknown AreaCode mutation op: %q", m.Op())
	}
}

// hooks and interceptors per client, for fast access.
type (
	hooks struct {
		AreaCode []ent.Hook
	}
	inters struct {
		AreaCode []ent.Interceptor
	}
)
