// Code generated by ent, DO NOT EDIT.

package ent

import (
	"bovs/internal/data/ent/areacode"
	"bovs/internal/data/ent/schema"
)

// The init function reads all schema descriptors with runtime code
// (default values, validators, hooks and policies) and stitches it
// to their package variables.
func init() {
	areacodeFields := schema.AreaCode{}.Fields()
	_ = areacodeFields
	// areacodeDescCode is the schema descriptor for code field.
	areacodeDescCode := areacodeFields[0].Descriptor()
	// areacode.CodeValidator is a validator for the "code" field. It is called by the builders before save.
	areacode.CodeValidator = areacodeDescCode.Validators[0].(func(int64) error)
	// areacodeDescName is the schema descriptor for name field.
	areacodeDescName := areacodeFields[1].Descriptor()
	// areacode.DefaultName holds the default value on creation for the name field.
	areacode.DefaultName = areacodeDescName.Default.(string)
	// areacodeDescPCode is the schema descriptor for p_code field.
	areacodeDescPCode := areacodeFields[3].Descriptor()
	// areacode.PCodeValidator is a validator for the "p_code" field. It is called by the builders before save.
	areacode.PCodeValidator = areacodeDescPCode.Validators[0].(func(int64) error)
}
