// Code generated by ent, DO NOT EDIT.

package migrate

import (
	"entgo.io/ent/dialect/entsql"
	"entgo.io/ent/dialect/sql/schema"
	"entgo.io/ent/schema/field"
)

var (
	// AreaCodeColumns holds the columns for the "area_code" table.
	AreaCodeColumns = []*schema.Column{
		{Name: "id", Type: field.TypeInt, Increment: true},
		{Name: "code", Type: field.TypeInt64},
		{Name: "name", Type: field.TypeString, Default: ""},
		{Name: "level", Type: field.TypeInt8},
		{Name: "p_code", Type: field.TypeInt64},
	}
	// AreaCodeTable holds the schema information for the "area_code" table.
	AreaCodeTable = &schema.Table{
		Name:       "area_code",
		Columns:    AreaCodeColumns,
		PrimaryKey: []*schema.Column{AreaCodeColumns[0]},
	}
	// Tables holds all the tables in the schema.
	Tables = []*schema.Table{
		AreaCodeTable,
	}
)

func init() {
	AreaCodeTable.Annotation = &entsql.Annotation{
		Table: "area_code",
	}
}
